FROM node:22-alpine AS build

ENV NODE_ENV=devlopment
WORKDIR /app

# copy only manifests first
COPY package*.json ./

RUN npm install 

# now copy the rest
COPY . .

RUN npm run build

From cgr.dev/chainguard/nginx:latest

ENV NODE_ENV=production

COPY --from=build /app/dist /usr/share/nginx/html

USER 65532:65532

EXPOSE 8080


