FROM node:20-alpine AS build

ENV NODE_ENV=devlopment
WORKDIR /app

# copy only manifests first
COPY package*.json ./

RUN npm install 

# now copy the rest
COPY . .

RUN npm run build

# From cgr.dev/chainguard/nginx:latest
FROM nginx:alpine AS production

ENV NODE_ENV=production

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80