FROM node:22-alpine AS build

ENV NODE_ENV=devlopment
WORKDIR /app

# copy only manifests first
COPY package*.json ./

RUN npm install

# now copy the rest
COPY . .

RUN npm run build

From cgr.dev/chainguard/node:latest

ENV NODE_ENV=production

COPY --from=build /app/dist/server.bundle.cjs ./

EXPOSE 9000
EXPOSE 8080

USER 65532:65532

CMD ["server.bundle.cjs"]  
